In [1]:
#mount google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import re

with open('/content/drive/MyDrive/Talendeur/candidate_skills_matrix.md', 'r', encoding='utf-8') as f:
    contenido = f.read()

# Quitar los guiones de las listas
csv_contenido = re.sub(r'^- ', '', contenido, flags=re.MULTILINE)

with open('candidate_skills.csv', 'w', encoding='utf-8') as f:
    f.write(csv_contenido)

In [3]:
candidate_skills_original=pd.read_csv('candidate_skills.csv')

In [4]:
candidate_skills_original

,candidate_id,first_name,surname,React,Python,JavaScript,AWS,Kubernetes,Azure,SQL,...,Data_analysis,Healthcare_knowledge,Technical_knowledge,Educational_expertise,Collaboration,Mentorship,Change_management,Creativity,Adaptability,Teamwork
0,1,John,Smith,1.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1
1,2,Sarah,Johnson,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1
2,3,Michael,Brown,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1
3,4,Jennifer,Davis,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1
4,5,Robert,Wilson,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
5,6,Lisa,Anderson,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1
6,7,David,Martinez,0.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1
7,8,Emma,Taylor,1.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1
8,9,Christopher,Moore,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1
9,10,Amanda,Garcia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1
10,11,Ryan,Thompson,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1
11,12,Ashley,White,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
12,13,Kevin,Clark,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1
13,14,Michelle,Lewis,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1
14,15,Daniel,Walker,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1
15,16,Nicole,Hall,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
16,17,Brian,Young,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1
17,18,Stephanie,King,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1
18,19,Anthony,Wright,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1
19,20,Rachel,Lopez,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
20,21,Matthew,Hill,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1
21,22,Lauren,Green,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
22,23,Jason,Adams,0.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1
23,24,Crystal,Baker,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1
24,25,Tyler,Gonzalez,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1
25,26,Samantha,Nelson,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1
26,27,Jordan,Carter,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1
27,28,Victoria,Mitchell,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
28,29,Gregory,Perez,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
29,30,Melissa,Roberts,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1
30,31,Stephen,Turner,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1
31,32,Angela,Phillips,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1
32,33,Eric,Campbell,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1
33,34,Sharon,Parker,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1
34,35,Nathan,Evans,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
35,36,Deborah,Edwards,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1 0 | 0 | 0 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 1 |
36,| 18 | Stephanie | King | 0 | 0 | 0 | 0 | 0 | ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,| 19 | Anthony | Wright | 0 | 1 | 0 | 1 | 0 | ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,| 20 | Rachel | Lopez | 0 | 0 | 0 | 0 | 0 | 0 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,| 21 | Matthew | Hill | 0 | 0 | 0 | 0 | 0 | 0 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,| 22 | Lauren | Green | 0 | 0 | 0 | 0 | 0 | 0 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,| 23 | Jason | Adams | 0 | 1 | 0 | 1 | 1 | 1 |...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,| 24 | Crystal | Baker | 0 | 0 | 0 | 0 | 0 | 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,| 25 | Tyler | Gonzalez | 0 | 0 | 1 | 0 | 0 | ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,| 26 | Samantha | Nelson | 0 | 1 | 0 | 0 | 0 |...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,| 27 | Jordan | Carter | 0 | 0 | 0 | 0 | 0 | 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,| 28 | Victoria | Mitchell | 0 | 0 | 0 | 0 | 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,| 29 | Gregory | Perez | 0 | 0 | 0 | 0 | 0 | 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,| 30 | Melissa | Roberts | 0 | 0 | 0 | 0 | 0 |...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,| 31 | Stephen | Turner | 0 | 0 | 0 | 0 | 0 | ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,| 32 | Angela | Phillips | 0 | 0 | 0 | 0 | 0 |...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,| 33 | Eric | Campbell | 0 | 0 | 1 | 0 | 0 | 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,| 34 | Sharon | Parker | 0 | 0 | 0 | 0 | 0 | 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,| 35 | Nathan | Evans | 0 | 0 | 0 | 0 | 0 | 0 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,| 36 | Deborah | Edwards | 0 | 0 | 0 | 0 | 0 |...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
candidate_skills_original.columns

Index(['candidate_id', 'first_name', 'surname', 'React', 'Python',
       'JavaScript', 'AWS', 'Kubernetes', 'Azure', 'SQL', 'Tableau', 'Excel',
       'Financial_modeling', 'CRM', 'Portfolio_management', 'Epic', 'HIPAA',
       'Clinical_trials', 'Salesforce', 'Jira', 'SAP', 'Google_Ads', 'SEO',
       'Digital_marketing', 'Adobe_Creative_Suite', 'Figma', 'CAD',
       'Lean_Six_Sigma', 'Process_mapping', 'AutoCAD', 'Project_management',
       'APIs', 'Database_management', 'Leadership', 'Team_leadership',
       'Project_leadership', 'Communication', 'Stakeholder_management',
       'Customer_service', 'Problem_solving', 'Analytical',
       'Strategic_thinking', 'Product_strategy', 'Business_modeling',
       'Data_analysis', 'Healthcare_knowledge', 'Technical_knowledge',
       'Educational_expertise', 'Collaboration', 'Mentorship',
       'Change_management', 'Creativity', 'Adaptability', 'Teamwork'],
      dtype='object')

In [6]:

# Create the first DataFrame with rows up to index 35 (inclusive)
candidate_skills_part1 = candidate_skills_original.iloc[:36]

# Create the second DataFrame with rows from index 36 onwards
candidate_skills_part2 = candidate_skills_original.iloc[36:]

# Display the head of both new DataFrames to confirm
display(candidate_skills_part1.head())
display(candidate_skills_part2.head())

,candidate_id,first_name,surname,React,Python,JavaScript,AWS,Kubernetes,Azure,SQL,...,Data_analysis,Healthcare_knowledge,Technical_knowledge,Educational_expertise,Collaboration,Mentorship,Change_management,Creativity,Adaptability,Teamwork
0,1,John,Smith,1.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1
1,2,Sarah,Johnson,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1
2,3,Michael,Brown,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1
3,4,Jennifer,Davis,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1
4,5,Robert,Wilson,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1

,candidate_id,first_name,surname,React,Python,JavaScript,AWS,Kubernetes,Azure,SQL,...,Data_analysis,Healthcare_knowledge,Technical_knowledge,Educational_expertise,Collaboration,Mentorship,Change_management,Creativity,Adaptability,Teamwork
36,| 18 | Stephanie | King | 0 | 0 | 0 | 0 | 0 | ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,| 19 | Anthony | Wright | 0 | 1 | 0 | 1 | 0 | ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,| 20 | Rachel | Lopez | 0 | 0 | 0 | 0 | 0 | 0 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,| 21 | Matthew | Hill | 0 | 0 | 0 | 0 | 0 | 0 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,| 22 | Lauren | Green | 0 | 0 | 0 | 0 | 0 | 0 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
candidate_skills_part2.columns

Index(['candidate_id', 'first_name', 'surname', 'React', 'Python',
       'JavaScript', 'AWS', 'Kubernetes', 'Azure', 'SQL', 'Tableau', 'Excel',
       'Financial_modeling', 'CRM', 'Portfolio_management', 'Epic', 'HIPAA',
       'Clinical_trials', 'Salesforce', 'Jira', 'SAP', 'Google_Ads', 'SEO',
       'Digital_marketing', 'Adobe_Creative_Suite', 'Figma', 'CAD',
       'Lean_Six_Sigma', 'Process_mapping', 'AutoCAD', 'Project_management',
       'APIs', 'Database_management', 'Leadership', 'Team_leadership',
       'Project_leadership', 'Communication', 'Stakeholder_management',
       'Customer_service', 'Problem_solving', 'Analytical',
       'Strategic_thinking', 'Product_strategy', 'Business_modeling',
       'Data_analysis', 'Healthcare_knowledge', 'Technical_knowledge',
       'Educational_expertise', 'Collaboration', 'Mentorship',
       'Change_management', 'Creativity', 'Adaptability', 'Teamwork'],
      dtype='object')

In [8]:
# We are going to correct the problems in the second part of the original matrix.

df_2_split=candidate_skills_part2['candidate_id'].str.lstrip('|').str.split('|', expand=True)

In [9]:
df_2_split.head()

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,54
36,18,Stephanie,King,0,0,0,0,0,0,0,...,0,0,0,1,1,1,1,1,1,
37,19,Anthony,Wright,0,1,0,1,0,1,1,...,0,1,0,1,0,1,0,1,1,
38,20,Rachel,Lopez,0,0,0,0,0,0,0,...,0,0,0,1,1,1,0,1,1,
39,21,Matthew,Hill,0,0,0,0,0,0,0,...,0,1,0,1,1,0,1,1,1,
40,22,Lauren,Green,0,0,0,0,0,0,1,...,0,0,0,1,1,1,0,1,1,

In [10]:
df_2_split.columns=['candidate_id', 'first_name', 'surname', 'React', 'Python',
       'JavaScript', 'AWS', 'Kubernetes', 'Azure', 'SQL', 'Tableau', 'Excel',
       'Financial_modeling', 'CRM', 'Portfolio_management', 'Epic', 'HIPAA',
       'Clinical_trials', 'Salesforce', 'Jira', 'SAP', 'Google_Ads', 'SEO',
       'Digital_marketing', 'Adobe_Creative_Suite', 'Figma', 'CAD',
       'Lean_Six_Sigma', 'Process_mapping', 'AutoCAD', 'Project_management',
       'APIs', 'Database_management', 'Leadership', 'Team_leadership',
       'Project_leadership', 'Communication', 'Stakeholder_management',
       'Customer_service', 'Problem_solving', 'Analytical',
       'Strategic_thinking', 'Product_strategy', 'Business_modeling',
       'Data_analysis', 'Healthcare_knowledge', 'Technical_knowledge',
       'Educational_expertise', 'Collaboration', 'Mentorship',
       'Change_management', 'Creativity', 'Adaptability', 'Teamwork','extra_1']

In [11]:
print(f"Columnas generadas por el split: {df_2_split.shape[1]}")

Columnas generadas por el split: 55

In [12]:
df_2_split.columns

Index(['candidate_id', 'first_name', 'surname', 'React', 'Python',
       'JavaScript', 'AWS', 'Kubernetes', 'Azure', 'SQL', 'Tableau', 'Excel',
       'Financial_modeling', 'CRM', 'Portfolio_management', 'Epic', 'HIPAA',
       'Clinical_trials', 'Salesforce', 'Jira', 'SAP', 'Google_Ads', 'SEO',
       'Digital_marketing', 'Adobe_Creative_Suite', 'Figma', 'CAD',
       'Lean_Six_Sigma', 'Process_mapping', 'AutoCAD', 'Project_management',
       'APIs', 'Database_management', 'Leadership', 'Team_leadership',
       'Project_leadership', 'Communication', 'Stakeholder_management',
       'Customer_service', 'Problem_solving', 'Analytical',
       'Strategic_thinking', 'Product_strategy', 'Business_modeling',
       'Data_analysis', 'Healthcare_knowledge', 'Technical_knowledge',
       'Educational_expertise', 'Collaboration', 'Mentorship',
       'Change_management', 'Creativity', 'Adaptability', 'Teamwork',
       'extra_1'],
      dtype='object')

In [13]:
df_2_split.head()

,candidate_id,first_name,surname,React,Python,JavaScript,AWS,Kubernetes,Azure,SQL,...,Healthcare_knowledge,Technical_knowledge,Educational_expertise,Collaboration,Mentorship,Change_management,Creativity,Adaptability,Teamwork,extra_1
36,18,Stephanie,King,0,0,0,0,0,0,0,...,0,0,0,1,1,1,1,1,1,
37,19,Anthony,Wright,0,1,0,1,0,1,1,...,0,1,0,1,0,1,0,1,1,
38,20,Rachel,Lopez,0,0,0,0,0,0,0,...,0,0,0,1,1,1,0,1,1,
39,21,Matthew,Hill,0,0,0,0,0,0,0,...,0,1,0,1,1,0,1,1,1,
40,22,Lauren,Green,0,0,0,0,0,0,1,...,0,0,0,1,1,1,0,1,1,

In [14]:
#delete last empty column
df_2_split=df_2_split.iloc[:,:-1]

In [15]:
#Let's vertically stack df1 and df2
candidate_skills_clean_full=pd.concat([candidate_skills_part1,df_2_split],axis=0)

In [16]:
candidate_skills_clean_full

,candidate_id,first_name,surname,React,Python,JavaScript,AWS,Kubernetes,Azure,SQL,...,Data_analysis,Healthcare_knowledge,Technical_knowledge,Educational_expertise,Collaboration,Mentorship,Change_management,Creativity,Adaptability,Teamwork
0,1,John,Smith,1.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1
1,2,Sarah,Johnson,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1
2,3,Michael,Brown,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1
3,4,Jennifer,Davis,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1
4,5,Robert,Wilson,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
5,6,Lisa,Anderson,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1
6,7,David,Martinez,0.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1
7,8,Emma,Taylor,1.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1
8,9,Christopher,Moore,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1
9,10,Amanda,Garcia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1
10,11,Ryan,Thompson,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1
11,12,Ashley,White,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
12,13,Kevin,Clark,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1
13,14,Michelle,Lewis,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1
14,15,Daniel,Walker,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1
15,16,Nicole,Hall,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
16,17,Brian,Young,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1
17,18,Stephanie,King,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1
18,19,Anthony,Wright,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1
19,20,Rachel,Lopez,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
20,21,Matthew,Hill,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1
21,22,Lauren,Green,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
22,23,Jason,Adams,0.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1
23,24,Crystal,Baker,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1
24,25,Tyler,Gonzalez,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1
25,26,Samantha,Nelson,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1
26,27,Jordan,Carter,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1
27,28,Victoria,Mitchell,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
28,29,Gregory,Perez,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
29,30,Melissa,Roberts,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1
30,31,Stephen,Turner,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1
31,32,Angela,Phillips,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1
32,33,Eric,Campbell,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1
33,34,Sharon,Parker,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1
34,35,Nathan,Evans,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1
35,36,Deborah,Edwards,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1 0 | 0 | 0 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 1 |
36,18,Stephanie,King,0,0,0,0,0,0,0,...,0,0,0,0,1,1,1,1,1,1
37,19,Anthony,Wright,0,1,0,1,0,1,1,...,0,0,1,0,1,0,1,0,1,1
38,20,Rachel,Lopez,0,0,0,0,0,0,0,...,1,0,0,0,1,1,1,0,1,1
39,21,Matthew,Hill,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,1,1,1
40,22,Lauren,Green,0,0,0,0,0,0,1,...,1,0,0,0,1,1,1,0,1,1
41,23,Jason,Adams,0,1,0,1,1,1,1,...,0,0,1,0,1,1,1,0,1,1
42,24,Crystal,Baker,0,0,0,0,0,0,0,...,0,0,0,0,1,1,1,1,1,1
43,25,Tyler,Gonzalez,0,0,1,0,0,0,0,...,1,0,0,0,1,1,1,1,1,1
44,26,Samantha,Nelson,0,1,0,0,0,0,1,...,1,0,1,0,1,1,1,1,1,1
45,27,Jordan,Carter,0,0,0,0,0,0,0,...,0,0,0,1,1,1,1,1,1,1
46,28,Victoria,Mitchell,0,0,0,0,0,0,0,...,1,0,0,0,1,1,1,0,1,1
47,29,Gregory,Perez,0,0,0,0,0,0,1,...,1,0,0,0,1,1,1,0,1,1
48,30,Melissa,Roberts,0,0,0,0,0,0,0,...,0,0,0,0,1,1,1,1,1,1
49,31,Stephen,Turner,0,0,0,0,0,0,1,...,0,0,1,0,1,1,1,1,1,1
50,32,Angela,Phillips,0,0,0,0,0,0,0,...,0,0,0,0,1,1,1,1,1,1
51,33,Eric,Campbell,0,0,1,0,0,0,0,...,0,0,1,0,1,1,0,1,1,1
52,34,Sharon,Parker,0,0,0,0,0,0,1,...,1,0,0,0,1,0,1,0,1,1
53,35,Nathan,Evans,0,0,0,0,0,0,0,...,0,1,0,0,1,1,1,0,1,1
54,36,Deborah,Edwards,0,0,0,0,0,0,1,...,1,0,0,0,1,0,1,0,1,1

In [17]:
#Remove one row that we couldn't improve ( candidadte_id=36,row=35)
candidate_skills_clean_full=candidate_skills_clean_full.drop(35)

In [18]:
#download candidate_skills to drive
candidate_skills_clean_full.to_csv('/content/drive/MyDrive/Talendeur/candidate_skills.csv', index=False)

In [19]:
#upload from drive job_positions
job_positions=pd.read_csv('/content/drive/MyDrive/Talendeur/job_postings.csv')

In [20]:
job_positions.head()

,first_name,surname,job_post,company,minimum_work_experience,max_work_experience,education,technical_skills,soft_skills,certifications,keyword_1,keyword_2,keyword_3,non_negotiable
0,TechCorp,Solutions,Senior Software Engineer,Microsoft,5,10,Bachelor Computer Science,"React, Node.js, Python, AWS","Leadership, Communication, Problem-solving","AWS Solutions Architect, Scrum Master",React,Leadership,Cloud,React
1,Global,Innovations,Management Consultant,Accenture,3,8,MBA Business Administration,"SQL, Tableau, PowerBI, Excel","Analytical, Strategic thinking, Client management","PMP, Six Sigma Black Belt",Strategy,Analytics,Consulting,MBA
2,Innovation,Labs,AI Research Scientist,Google,7,12,PhD Computer Science,"Python, TensorFlow, PyTorch, R","Research, Innovation, Critical thinking","Google Cloud Professional, IEEE Member",AI,Research,Machine-learning,PhD
3,NextGen,Solutions,Healthcare IT Specialist,Epic Systems,4,9,Bachelor Health Informatics,"Epic, HL7, SQL, JavaScript","Healthcare knowledge, Attention to detail, Col...","Epic Certified, HIMSS Member",Healthcare,Epic,Integration,Epic
4,Digital,Dynamics,Full Stack Developer,Shopify,3,7,Bachelor Software Engineering,"React, Node.js, MongoDB, GraphQL","Creativity, Adaptability, Teamwork","MongoDB Certified, React Developer",E-commerce,Full-stack,JavaScript,MongoDB

In [21]:
#Converting the string variable in technical skills and soft skills in binary variables
# creating a separate space to work with the data, to keep the original matrix clean
#define a new frame from candidate_skills from the fourth column up to the end
candidate_sk_=candidate_skills_clean_full.iloc[:,3:]
#define two frames for skills in the job positions frame
skill_tech_col=job_positions['technical_skills']
skill_soft_col=job_positions['soft_skills']
#defining a conversion function from string to vector

In [22]:
skill_tech_col.head()

0         React, Node.js, Python, AWS
1        SQL, Tableau, PowerBI, Excel
2      Python, TensorFlow, PyTorch, R
3          Epic, HL7, SQL, JavaScript
4    React, Node.js, MongoDB, GraphQL
Name: technical_skills, dtype: object

In [23]:
skill_soft_col

0            Leadership, Communication, Problem-solving
1     Analytical, Strategic thinking, Client management
2               Research, Innovation, Critical thinking
3     Healthcare knowledge, Attention to detail, Col...
4                    Creativity, Adaptability, Teamwork
5     Product vision, Stakeholder management, User e...
6       Financial modeling, Due diligence, Presentation
7     Change management, Client relations, Problem s...
8      Creative vision, Brand strategy, Team leadership
9     Architecture design, Technical leadership, Cli...
10    Strategic thinking, Executive presence, Proble...
11    Financial analysis, Market research, Communica...
12         Mentorship, Network building, Event planning
13      Research methodology, Innovation, Collaboration
14    Campaign optimization, Data analysis, Creative...
15    Strategic thinking, Client management, Leadership
16     Mentorship, Entrepreneurship, Strategic guidance
17    Client relationships, Financial planning, Trus...
18    Healthcare operations, Team leadership, Compli...
19    Technical consulting, Customer success, Proble...
20        Retail domain, Agile development, Code review
21    Operations excellence, Team leadership, Contin...
22    Attention to detail, Patient interaction, Prot...
23    Educational expertise, User empathy, Product s...
24    Customer service, Team leadership, Cultural se...
25           Community engagement, Leadership, Advocacy
26    Risk assessment, Problem solving, Attention to...
27    Logistics optimization, Vendor management, Pro...
28    Project leadership, Stakeholder management, Su...
29    Sports knowledge, Creative campaigns, Relation...
30    Healthcare leadership, Policy knowledge, Team ...
31    Relationship building, Risk evaluation, Commun...
32    Customer service, Team leadership, Technical k...
Name: soft_skills, dtype: object

In [24]:
#Import special library
from sklearn.preprocessing import MultiLabelBinarizer

In [25]:
#convert strings in to lists
skill_tech_col=skill_tech_col.str.split(',')
skill_tech_col=skill_tech_col.apply(lambda lst: [s.strip() for s in lst])
skill_soft_col=skill_soft_col.str.split(',')
skill_soft_col=skill_soft_col.apply(lambda lst: [s.strip() for s in lst])

In [26]:
skill_tech_col.head()

0         [React, Node.js, Python, AWS]
1        [SQL, Tableau, PowerBI, Excel]
2      [Python, TensorFlow, PyTorch, R]
3          [Epic, HL7, SQL, JavaScript]
4    [React, Node.js, MongoDB, GraphQL]
Name: technical_skills, dtype: object

In [27]:
skill_soft_col.head()

0         [Leadership, Communication, Problem-solving]
1    [Analytical, Strategic thinking, Client manage...
2            [Research, Innovation, Critical thinking]
3    [Healthcare knowledge, Attention to detail, Co...
4                 [Creativity, Adaptability, Teamwork]
Name: soft_skills, dtype: object

In [28]:
#Creating clean lists before using the binarizer
skill_tech_col_clean = skill_tech_col.apply(
    lambda x: [s.strip().lower() for s in x] if isinstance(x, list) else []
)
skill_soft_col_clean = skill_soft_col.apply(
    lambda x: [s.strip().lower() for s in x] if isinstance(x, list) else []
)

In [29]:
skill_tech_col_clean.head()

0         [react, node.js, python, aws]
1        [sql, tableau, powerbi, excel]
2      [python, tensorflow, pytorch, r]
3          [epic, hl7, sql, javascript]
4    [react, node.js, mongodb, graphql]
Name: technical_skills, dtype: object

In [30]:
skill_soft_col_clean.head()

0         [leadership, communication, problem-solving]
1    [analytical, strategic thinking, client manage...
2            [research, innovation, critical thinking]
3    [healthcare knowledge, attention to detail, co...
4                 [creativity, adaptability, teamwork]
Name: soft_skills, dtype: object

In [31]:
mbinarizer=MultiLabelBinarizer()

In [34]:
#Apply binarizer to tech skills
mbinarizer_tech = MultiLabelBinarizer()
tech_matrix = mbinarizer_tech.fit_transform(skill_tech_col_clean)

#Apply binarizer to soft skills
mbinarizer_soft = MultiLabelBinarizer()
soft_matrix = mbinarizer_soft.fit_transform(skill_soft_col_clean)

In [37]:
#Convert to a df
tech_skills_bin = pd.DataFrame(tech_matrix, columns=mbinarizer_tech.classes_, index=job_positions.index)

In [38]:
#Convert to df
soft_skills_bin=pd.DataFrame(soft_matrix,columns=mbinarizer.classes_,index=job_positions.index)

In [36]:
# Convert soft skills matrix to a df
soft_skills_bin = pd.DataFrame(soft_matrix, columns=mbinarizer_soft.classes_)
display(soft_skills_bin.head())

,adaptability,advocacy,agile development,analytical,architecture design,attention to detail,brand strategy,campaign optimization,change management,client consulting,...,sustainability focus,team leadership,team management,teamwork,technical consulting,technical knowledge,technical leadership,trust building,user empathy,vendor management
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [39]:
jb_full_skills=pd.concat([job_positions,tech_skills_bin,soft_skills_bin],axis=1)

In [40]:
jb_full_skills.head()

,first_name,surname,job_post,company,minimum_work_experience,max_work_experience,education,technical_skills,soft_skills,certifications,...,sustainability focus,team leadership,team management,teamwork,technical consulting,technical knowledge,technical leadership,trust building,user empathy,vendor management
0,TechCorp,Solutions,Senior Software Engineer,Microsoft,5,10,Bachelor Computer Science,"React, Node.js, Python, AWS","Leadership, Communication, Problem-solving","AWS Solutions Architect, Scrum Master",...,0,0,0,0,0,0,0,0,0,0
1,Global,Innovations,Management Consultant,Accenture,3,8,MBA Business Administration,"SQL, Tableau, PowerBI, Excel","Analytical, Strategic thinking, Client management","PMP, Six Sigma Black Belt",...,0,0,0,0,0,0,0,0,0,0
2,Innovation,Labs,AI Research Scientist,Google,7,12,PhD Computer Science,"Python, TensorFlow, PyTorch, R","Research, Innovation, Critical thinking","Google Cloud Professional, IEEE Member",...,0,0,0,0,0,0,0,0,0,0
3,NextGen,Solutions,Healthcare IT Specialist,Epic Systems,4,9,Bachelor Health Informatics,"Epic, HL7, SQL, JavaScript","Healthcare knowledge, Attention to detail, Col...","Epic Certified, HIMSS Member",...,0,0,0,0,0,0,0,0,0,0
4,Digital,Dynamics,Full Stack Developer,Shopify,3,7,Bachelor Software Engineering,"React, Node.js, MongoDB, GraphQL","Creativity, Adaptability, Teamwork","MongoDB Certified, React Developer",...,0,0,0,1,0,0,0,0,0,0

In [41]:
#dropping the original columns
jb_full_skill_clean=jb_full_skills.drop(columns=['technical_skills','soft_skills'])

In [57]:
#Compare the columns of the two dataframes to be used in the cosine similarity process candidate_skills_clean_full and jb_full_skill_clean
skill_col_fullcandidate=candidate_skills_clean_full.columns[3:]
skill_col_fullcandidate = [col.lower() for col in skill_col_fullcandidate]
skill_col_fulljob=jb_full_skill_clean.columns[12:]
skill_col_fulljob = [col.lower() for col in skill_col_fulljob]

In [58]:
#convert in to sets
skill_col_fullcandidate=set(skill_col_fullcandidate)
skill_col_fulljob=set(skill_col_fulljob)

In [59]:
#Let's see the share columns
share_columns=skill_col_fullcandidate&skill_col_fulljob

In [60]:
share_columns

{'adaptability',
 'analytical',
 'apis',
 'autocad',
 'aws',
 'azure',
 'cad',
 'collaboration',
 'communication',
 'creativity',
 'crm',
 'epic',
 'excel',
 'figma',
 'hipaa',
 'javascript',
 'jira',
 'kubernetes',
 'leadership',
 'mentorship',
 'python',
 'react',
 'salesforce',
 'sap',
 'seo',
 'sql',
 'tableau',
 'teamwork'}

In [61]:
#Skills in candidates not present in job positions
only_candidate_skills=skill_col_fullcandidate - skill_col_fulljob

In [62]:
only_candidate_skills

{'adobe_creative_suite',
 'business_modeling',
 'change_management',
 'clinical_trials',
 'customer_service',
 'data_analysis',
 'database_management',
 'digital_marketing',
 'educational_expertise',
 'financial_modeling',
 'google_ads',
 'healthcare_knowledge',
 'lean_six_sigma',
 'portfolio_management',
 'problem_solving',
 'process_mapping',
 'product_strategy',
 'project_leadership',
 'project_management',
 'stakeholder_management',
 'strategic_thinking',
 'team_leadership',
 'technical_knowledge'}

In [63]:
#Skills that appear in job postings that are not present on candidates profiles
only_job_skills=skill_col_fulljob-skill_col_fullcandidate

In [68]:
#Create two dataframes that have only the commmon skills
#order the columns
share_columns_ordered=sorted(share_columns)
df_candidate=candidate_skills_clean_full.copy()
df_candidate.columns = df_candidate.columns.str.lower()
df_candidate=df_candidate[share_columns_ordered]
df_job=jb_full_skill_clean[share_columns_ordered]

In [70]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity= cosine_similarity(df_candidate, df_job)

In [72]:
import numpy as np

In [74]:
for job_idx in range(cosine_similarity.shape[1]):
  job_similarities=cosine_similarity[:,job_idx]
  sorted_indices=np.argsort(job_similarities)[::-1]
  top_5_indices=sorted_indices[:5]

In [76]:
  print(f"\nTRABAJO {job_idx}:")
  print("Top 5:", sorted_indices[:5], "Scores:", job_similarities[sorted_indices[:5]])
  print("Bottom 3:", sorted_indices[-3:][::-1], "Scores:", job_similarities[sorted_indices[-3:][::-1]])

TRABAJO 32:
Top 5: [37 19 41 35 31] Scores: [0.31622777 0.31622777 0.30151134 0.30151134 0.30151134]
Bottom 3: [0 2 3] Scores: [0. 0. 0.]

In [82]:
job_columns = ['job_post', 'company', 'minimum_work_experience', 'max_work_experience', 'education', 'certifications']
candidate_columns = ['candidate_id', 'first_name', 'surname']

for job_idx in range(cosine_similarity.shape[1]):
    job_similarities = cosine_similarity[:, job_idx]
    sorted_indices = np.argsort(job_similarities)[::-1]
    top_5_indices = sorted_indices[:5]

    print(f"\n--- Job details ---")
    job_row = jb_full_skill_clean.iloc[job_idx]
    for col in job_columns:
        if col in jb_full_skill_clean.columns:
            print(f"{col}: {job_row[col]}")

    print(f"\nTOP 5 CANDIDATES:")
    for rank, candidate_idx in enumerate(top_5_indices, 1):
        similarity_score = job_similarities[candidate_idx]
        candidate_row = candidate_skills_clean_full.iloc[candidate_idx]

        print(f"\n{rank}. Candidate {candidate_skills_clean_full.iloc[candidate_idx]['candidate_id']} (Similitud: {similarity_score:.3f})")
        for col in candidate_columns:
            if col in candidate_skills_clean_full.columns:
                print(f"   {col}: {candidate_row[col]}")

--- Job details ---
job_post: Senior Software Engineer
company: Microsoft
minimum_work_experience: 5
max_work_experience: 10
education: Bachelor Computer Science
certifications: AWS Solutions Architect, Scrum Master

TOP 5 CANDIDATES:

1. Candidate 1 (Similitud: 0.542)
   candidate_id: 1
   first_name: John
   surname: Smith

2. Candidate 3 (Similitud: 0.527)
   candidate_id: 3
   first_name: Michael
   surname: Brown

3. Candidate 9 (Similitud: 0.496)
   candidate_id: 9
   first_name: Christopher
   surname: Moore

4. Candidate 19 (Similitud: 0.496)
   candidate_id: 19
   first_name: Anthony
   surname: Wright

5. Candidate  19  (Similitud: 0.496)
   candidate_id:  19
   first_name:  Anthony
   surname:  Wright

--- Job details ---
job_post: Management Consultant
company: Accenture
minimum_work_experience: 3
max_work_experience: 8
education: MBA Business Administration
certifications: PMP, Six Sigma Black Belt

TOP 5 CANDIDATES:

1. Candidate  34  (Similitud: 0.632)
   candidate_id:  34
   first_name:  Sharon
   surname:  Parker

2. Candidate 34 (Similitud: 0.632)
   candidate_id: 34
   first_name: Sharon
   surname: Parker

3. Candidate 6 (Similitud: 0.632)
   candidate_id: 6
   first_name: Lisa
   surname: Anderson

4. Candidate 13 (Similitud: 0.603)
   candidate_id: 13
   first_name: Kevin
   surname: Clark

5. Candidate  36  (Similitud: 0.577)
   candidate_id:  36
   first_name:  Deborah
   surname:  Edwards

--- Job details ---
job_post: AI Research Scientist
company: Google
minimum_work_experience: 7
max_work_experience: 12
education: PhD Computer Science
certifications: Google Cloud Professional, IEEE Member

TOP 5 CANDIDATES:

1. Candidate 13 (Similitud: 0.302)
   candidate_id: 13
   first_name: Kevin
   surname: Clark

2. Candidate 15 (Similitud: 0.289)
   candidate_id: 15
   first_name: Daniel
   surname: Walker

3. Candidate 9 (Similitud: 0.277)
   candidate_id: 9
   first_name: Christopher
   surname: Moore

4. Candidate 19 (Similitud: 0.277)
   candidate_id: 19
   first_name: Anthony
   surname: Wright

5. Candidate  19  (Similitud: 0.277)
   candidate_id:  19
   first_name:  Anthony
   surname:  Wright

--- Job details ---
job_post: Healthcare IT Specialist
company: Epic Systems
minimum_work_experience: 4
max_work_experience: 9
education: Bachelor Health Informatics
certifications: Epic Certified, HIMSS Member

TOP 5 CANDIDATES:

1. Candidate 15 (Similitud: 0.433)
   candidate_id: 15
   first_name: Daniel
   surname: Walker

2. Candidate 11 (Similitud: 0.401)
   candidate_id: 11
   first_name: Ryan
   surname: Thompson

3. Candidate 1 (Similitud: 0.364)
   candidate_id: 1
   first_name: John
   surname: Smith

4. Candidate 3 (Similitud: 0.354)
   candidate_id: 3
   first_name: Michael
   surname: Brown

5. Candidate 8 (Similitud: 0.344)
   candidate_id: 8
   first_name: Emma
   surname: Taylor

--- Job details ---
job_post: Full Stack Developer
company: Shopify
minimum_work_experience: 3
max_work_experience: 7
education: Bachelor Software Engineering
certifications: MongoDB Certified, React Developer

TOP 5 CANDIDATES:

1. Candidate 11 (Similitud: 0.535)
   candidate_id: 11
   first_name: Ryan
   surname: Thompson

2. Candidate  27  (Similitud: 0.500)
   candidate_id:  27
   first_name:  Jordan
   surname:  Carter

3. Candidate 27 (Similitud: 0.500)
   candidate_id: 27
   first_name: Jordan
   surname: Carter

4. Candidate 1 (Similitud: 0.485)
   candidate_id: 1
   first_name: John
   surname: Smith

5. Candidate 4 (Similitud: 0.474)
   candidate_id: 4
   first_name: Jennifer
   surname: Davis

--- Job details ---
job_post: Product Manager
company: Salesforce
minimum_work_experience: 4
max_work_experience: 8
education: MBA Technology Management
certifications: Salesforce Certified, Product Owner

TOP 5 CANDIDATES:

1. Candidate 11 (Similitud: 0.309)
   candidate_id: 11
   first_name: Ryan
   surname: Thompson

2. Candidate 5 (Similitud: 0.309)
   candidate_id: 5
   first_name: Robert
   surname: Wilson

3. Candidate 8 (Similitud: 0.265)
   candidate_id: 8
   first_name: Emma
   surname: Taylor

4. Candidate 20 (Similitud: 0.183)
   candidate_id: 20
   first_name: Rachel
   surname: Lopez

5. Candidate  20  (Similitud: 0.183)
   candidate_id:  20
   first_name:  Rachel
   surname:  Lopez

--- Job details ---
job_post: Investment Analyst
company: Goldman Sachs
minimum_work_experience: 2
max_work_experience: 6
education: Bachelor Finance
certifications: CFA Level II, Series 7

TOP 5 CANDIDATES:

1. Candidate 13 (Similitud: 0.426)
   candidate_id: 13
   first_name: Kevin
   surname: Clark

2. Candidate 15 (Similitud: 0.408)
   candidate_id: 15
   first_name: Daniel
   surname: Walker

3. Candidate 9 (Similitud: 0.392)
   candidate_id: 9
   first_name: Christopher
   surname: Moore

4. Candidate 19 (Similitud: 0.392)
   candidate_id: 19
   first_name: Anthony
   surname: Wright

5. Candidate  19  (Similitud: 0.392)
   candidate_id:  19
   first_name:  Anthony
   surname:  Wright

--- Job details ---
job_post: Business Process Consultant
company: Deloitte
minimum_work_experience: 5
max_work_experience: 10
education: Master Business Administration
certifications: Six Sigma Black Belt, SAP Certified

TOP 5 CANDIDATES:

1. Candidate  34  (Similitud: 0.447)
   candidate_id:  34
   first_name:  Sharon
   surname:  Parker

2. Candidate 34 (Similitud: 0.447)
   candidate_id: 34
   first_name: Sharon
   surname: Parker

3. Candidate 6 (Similitud: 0.447)
   candidate_id: 6
   first_name: Lisa
   surname: Anderson

4. Candidate 13 (Similitud: 0.426)
   candidate_id: 13
   first_name: Kevin
   surname: Clark

5. Candidate  36  (Similitud: 0.408)
   candidate_id:  36
   first_name:  Deborah
   surname:  Edwards

--- Job details ---
job_post: Art Director
company: Ogilvy
minimum_work_experience: 6
max_work_experience: 12
education: Bachelor Fine Arts
certifications: Adobe Certified Expert, Cannes Lions Judge

TOP 5 CANDIDATES:

1. Candidate 4 (Similitud: 0.316)
   candidate_id: 4
   first_name: Jennifer
   surname: Davis

2. Candidate  33  (Similitud: 0.302)
   candidate_id:  33
   first_name:  Eric
   surname:  Campbell

3. Candidate 33 (Similitud: 0.302)
   candidate_id: 33
   first_name: Eric
   surname: Campbell

4. Candidate  18  (Similitud: 0.302)
   candidate_id:  18
   first_name:  Stephanie
   surname:  King

5. Candidate 18 (Similitud: 0.302)
   candidate_id: 18
   first_name: Stephanie
   surname: King

--- Job details ---
job_post: Cloud Solutions Architect
company: IBM
minimum_work_experience: 7
max_work_experience: 15
education: Master Computer Science
certifications: AWS Solutions Architect, Azure Expert

TOP 5 CANDIDATES:

1. Candidate 7 (Similitud: 0.463)
   candidate_id: 7
   first_name: David
   surname: Martinez

2. Candidate  23  (Similitud: 0.447)
   candidate_id:  23
   first_name:  Jason
   surname:  Adams

3. Candidate 23 (Similitud: 0.447)
   candidate_id: 23
   first_name: Jason
   surname: Adams

4. Candidate 3 (Similitud: 0.408)
   candidate_id: 3
   first_name: Michael
   surname: Brown

5. Candidate 19 (Similitud: 0.320)
   candidate_id: 19
   first_name: Anthony
   surname: Wright

--- Job details ---
job_post: Strategy Consultant
company: McKinsey
minimum_work_experience: 3
max_work_experience: 8
education: MBA Strategy
certifications: McKinsey Certified, PMP

TOP 5 CANDIDATES:

1. Candidate  34  (Similitud: 0.316)
   candidate_id:  34
   first_name:  Sharon
   surname:  Parker

2. Candidate 34 (Similitud: 0.316)
   candidate_id: 34
   first_name: Sharon
   surname: Parker

3. Candidate 6 (Similitud: 0.316)
   candidate_id: 6
   first_name: Lisa
   surname: Anderson

4. Candidate 13 (Similitud: 0.302)
   candidate_id: 13
   first_name: Kevin
   surname: Clark

5. Candidate 10 (Similitud: 0.302)
   candidate_id: 10
   first_name: Amanda
   surname: Garcia

--- Job details ---
job_post: Due Diligence Analyst
company: Sequoia Capital
minimum_work_experience: 2
max_work_experience: 5
education: Bachelor Business
certifications: CFA Candidate, Venture Capital Cert

TOP 5 CANDIDATES:

1. Candidate 13 (Similitud: 0.603)
   candidate_id: 13
   first_name: Kevin
   surname: Clark

2. Candidate 15 (Similitud: 0.577)
   candidate_id: 15
   first_name: Daniel
   surname: Walker

3. Candidate 9 (Similitud: 0.555)
   candidate_id: 9
   first_name: Christopher
   surname: Moore

4. Candidate 19 (Similitud: 0.555)
   candidate_id: 19
   first_name: Anthony
   surname: Wright

5. Candidate  19  (Similitud: 0.555)
   candidate_id:  19
   first_name:  Anthony
   surname:  Wright

--- Job details ---
job_post: Program Manager
company: Y Combinator
minimum_work_experience: 3
max_work_experience: 7
education: Bachelor Business Administration
certifications: Startup Accelerator Cert, PMP

TOP 5 CANDIDATES:

1. Candidate  20  (Similitud: 0.447)
   candidate_id:  20
   first_name:  Rachel
   surname:  Lopez

2. Candidate 20 (Similitud: 0.447)
   candidate_id: 20
   first_name: Rachel
   surname: Lopez

3. Candidate  24  (Similitud: 0.426)
   candidate_id:  24
   first_name:  Crystal
   surname:  Baker

4. Candidate  18  (Similitud: 0.426)
   candidate_id:  18
   first_name:  Stephanie
   surname:  King

5. Candidate 32 (Similitud: 0.426)
   candidate_id: 32
   first_name: Angela
   surname: Phillips

--- Job details ---
job_post: Research Engineer
company: Bell Labs
minimum_work_experience: 5
max_work_experience: 12
education: PhD Engineering
certifications: IEEE Member, Patent Holder

TOP 5 CANDIDATES:

1. Candidate  26  (Similitud: 0.463)
   candidate_id:  26
   first_name:  Samantha
   surname:  Nelson

2. Candidate 26 (Similitud: 0.463)
   candidate_id: 26
   first_name: Samantha
   surname: Nelson

3. Candidate 13 (Similitud: 0.348)
   candidate_id: 13
   first_name: Kevin
   surname: Clark

4. Candidate 15 (Similitud: 0.333)
   candidate_id: 15
   first_name: Daniel
   surname: Walker

5. Candidate 31 (Similitud: 0.333)
   candidate_id: 31
   first_name: Stephen
   surname: Turner

--- Job details ---
job_post: Performance Marketing Manager
company: Meta
minimum_work_experience: 4
max_work_experience: 8
education: Bachelor Marketing
certifications: Google Ads Certified, Facebook Blueprint

TOP 5 CANDIDATES:

1. Candidate 14 (Similitud: 0.289)
   candidate_id: 14
   first_name: Michelle
   surname: Lewis

2. Candidate 2 (Similitud: 0.277)
   candidate_id: 2
   first_name: Sarah
   surname: Johnson

3. Candidate  25  (Similitud: 0.267)
   candidate_id:  25
   first_name:  Tyler
   surname:  Gonzalez

4. Candidate 25 (Similitud: 0.267)
   candidate_id: 25
   first_name: Tyler
   surname: Gonzalez

5. Candidate  34  (Similitud: 0.000)
   candidate_id:  34
   first_name:  Sharon
   surname:  Parker

--- Job details ---
job_post: Senior Consultant
company: Boston Consulting Group
minimum_work_experience: 4
max_work_experience: 10
education: MBA Business
certifications: BCG Certified, Six Sigma

TOP 5 CANDIDATES:

1. Candidate  34  (Similitud: 0.632)
   candidate_id:  34
   first_name:  Sharon
   surname:  Parker

2. Candidate 34 (Similitud: 0.632)
   candidate_id: 34
   first_name: Sharon
   surname: Parker

3. Candidate 6 (Similitud: 0.632)
   candidate_id: 6
   first_name: Lisa
   surname: Anderson

4. Candidate 13 (Similitud: 0.603)
   candidate_id: 13
   first_name: Kevin
   surname: Clark

5. Candidate  36  (Similitud: 0.577)
   candidate_id:  36
   first_name:  Deborah
   surname:  Edwards

--- Job details ---
job_post: Startup Mentor
company: Techstars
minimum_work_experience: 5
max_work_experience: 15
education: Master Business
certifications: Certified Mentor, Angel Investor

TOP 5 CANDIDATES:

1. Candidate  20  (Similitud: 0.447)
   candidate_id:  20
   first_name:  Rachel
   surname:  Lopez

2. Candidate 20 (Similitud: 0.447)
   candidate_id: 20
   first_name: Rachel
   surname: Lopez

3. Candidate  24  (Similitud: 0.426)
   candidate_id:  24
   first_name:  Crystal
   surname:  Baker

4. Candidate  18  (Similitud: 0.426)
   candidate_id:  18
   first_name:  Stephanie
   surname:  King

5. Candidate 32 (Similitud: 0.426)
   candidate_id: 32
   first_name: Angela
   surname: Phillips

--- Job details ---
job_post: Wealth Manager
company: Morgan Stanley
minimum_work_experience: 3
max_work_experience: 10
education: Bachelor Finance
certifications: CFP, Series 7 & 66

TOP 5 CANDIDATES:

1. Candidate  20  (Similitud: 0.447)
   candidate_id:  20
   first_name:  Rachel
   surname:  Lopez

2. Candidate 20 (Similitud: 0.447)
   candidate_id: 20
   first_name: Rachel
   surname: Lopez

3. Candidate  24  (Similitud: 0.426)
   candidate_id:  24
   first_name:  Crystal
   surname:  Baker

4. Candidate  18  (Similitud: 0.426)
   candidate_id:  18
   first_name:  Stephanie
   surname:  King

5. Candidate 32 (Similitud: 0.426)
   candidate_id: 32
   first_name: Angela
   surname: Phillips

--- Job details ---
job_post: Clinical Operations Manager
company: Kaiser Permanente
minimum_work_experience: 6
max_work_experience: 12
education: Master Healthcare Administration
certifications: HIMSS Certified, Healthcare MBA

TOP 5 CANDIDATES:

1. Candidate  35  (Similitud: 0.447)
   candidate_id:  35
   first_name:  Nathan
   surname:  Evans

2. Candidate 35 (Similitud: 0.447)
   candidate_id: 35
   first_name: Nathan
   surname: Evans

3. Candidate  34  (Similitud: 0.000)
   candidate_id:  34
   first_name:  Sharon
   surname:  Parker

4. Candidate  33  (Similitud: 0.000)
   candidate_id:  33
   first_name:  Eric
   surname:  Campbell

5. Candidate  32  (Similitud: 0.000)
   candidate_id:  32
   first_name:  Angela
   surname:  Phillips

--- Job details ---
job_post: Solutions Engineer
company: Snowflake
minimum_work_experience: 4
max_work_experience: 9
education: Bachelor Computer Science
certifications: Snowflake Certified, Cloud Solutions

TOP 5 CANDIDATES:

1. Candidate 15 (Similitud: 0.500)
   candidate_id: 15
   first_name: Daniel
   surname: Walker

2. Candidate  19  (Similitud: 0.480)
   candidate_id:  19
   first_name:  Anthony
   surname:  Wright

3. Candidate 19 (Similitud: 0.480)
   candidate_id: 19
   first_name: Anthony
   surname: Wright

4. Candidate 9 (Similitud: 0.480)
   candidate_id: 9
   first_name: Christopher
   surname: Moore

5. Candidate 7 (Similitud: 0.463)
   candidate_id: 7
   first_name: David
   surname: Martinez

--- Job details ---
job_post: Software Developer
company: Square
minimum_work_experience: 3
max_work_experience: 8
education: Bachelor Software Engineering
certifications: Oracle Certified, Agile Practitioner

TOP 5 CANDIDATES:

1. Candidate 11 (Similitud: 0.267)
   candidate_id: 11
   first_name: Ryan
   surname: Thompson

2. Candidate 1 (Similitud: 0.243)
   candidate_id: 1
   first_name: John
   surname: Smith

3. Candidate 3 (Similitud: 0.236)
   candidate_id: 3
   first_name: Michael
   surname: Brown

4. Candidate 8 (Similitud: 0.229)
   candidate_id: 8
   first_name: Emma
   surname: Taylor

5. Candidate  36  (Similitud: 0.000)
   candidate_id:  36
   first_name:  Deborah
   surname:  Edwards

--- Job details ---
job_post: Operations Manager
company: General Electric
minimum_work_experience: 7
max_work_experience: 15
education: Master Industrial Engineering
certifications: Six Sigma Black Belt, Lean Certified

TOP 5 CANDIDATES:

1. Candidate  36  (Similitud: 0.000)
   candidate_id:  36
   first_name:  Deborah
   surname:  Edwards

2. Candidate  35  (Similitud: 0.000)
   candidate_id:  35
   first_name:  Nathan
   surname:  Evans

3. Candidate  34  (Similitud: 0.000)
   candidate_id:  34
   first_name:  Sharon
   surname:  Parker

4. Candidate  33  (Similitud: 0.000)
   candidate_id:  33
   first_name:  Eric
   surname:  Campbell

5. Candidate  32  (Similitud: 0.000)
   candidate_id:  32
   first_name:  Angela
   surname:  Phillips

--- Job details ---
job_post: Clinical Research Coordinator
company: Mayo Clinic
minimum_work_experience: 4
max_work_experience: 8
education: Bachelor Life Sciences
certifications: GCP Certified, Clinical Research

TOP 5 CANDIDATES:

1. Candidate  36  (Similitud: 0.000)
   candidate_id:  36
   first_name:  Deborah
   surname:  Edwards

2. Candidate  35  (Similitud: 0.000)
   candidate_id:  35
   first_name:  Nathan
   surname:  Evans

3. Candidate  34  (Similitud: 0.000)
   candidate_id:  34
   first_name:  Sharon
   surname:  Parker

4. Candidate  33  (Similitud: 0.000)
   candidate_id:  33
   first_name:  Eric
   surname:  Campbell

5. Candidate  32  (Similitud: 0.000)
   candidate_id:  32
   first_name:  Angela
   surname:  Phillips

--- Job details ---
job_post: EdTech Product Manager
company: Coursera
minimum_work_experience: 3
max_work_experience: 7
education: Master Education Technology
certifications: Google Analytics, Product Management

TOP 5 CANDIDATES:

1. Candidate  34  (Similitud: 0.316)
   candidate_id:  34
   first_name:  Sharon
   surname:  Parker

2. Candidate 34 (Similitud: 0.316)
   candidate_id: 34
   first_name: Sharon
   surname: Parker

3. Candidate 6 (Similitud: 0.316)
   candidate_id: 6
   first_name: Lisa
   surname: Anderson

4. Candidate 17 (Similitud: 0.302)
   candidate_id: 17
   first_name: Brian
   surname: Young

5. Candidate 13 (Similitud: 0.302)
   candidate_id: 13
   first_name: Kevin
   surname: Clark

--- Job details ---
job_post: Hotel Operations Manager
company: Marriott
minimum_work_experience: 5
max_work_experience: 12
education: Bachelor Hospitality Management
certifications: Certified Hotel Administrator, Revenue Management

TOP 5 CANDIDATES:

1. Candidate  36  (Similitud: 0.000)
   candidate_id:  36
   first_name:  Deborah
   surname:  Edwards

2. Candidate  35  (Similitud: 0.000)
   candidate_id:  35
   first_name:  Nathan
   surname:  Evans

3. Candidate  34  (Similitud: 0.000)
   candidate_id:  34
   first_name:  Sharon
   surname:  Parker

4. Candidate  33  (Similitud: 0.000)
   candidate_id:  33
   first_name:  Eric
   surname:  Campbell

5. Candidate  32  (Similitud: 0.000)
   candidate_id:  32
   first_name:  Angela
   surname:  Phillips

--- Job details ---
job_post: Program Director
company: United Way
minimum_work_experience: 6
max_work_experience: 15
education: Master Social Work
certifications: Certified Fund Raising Executive, MSW

TOP 5 CANDIDATES:

1. Candidate  28  (Similitud: 0.354)
   candidate_id:  28
   first_name:  Victoria
   surname:  Mitchell

2. Candidate 28 (Similitud: 0.354)
   candidate_id: 28
   first_name: Victoria
   surname: Mitchell

3. Candidate 27 (Similitud: 0.333)
   candidate_id: 27
   first_name: Jordan
   surname: Carter

4. Candidate  27  (Similitud: 0.333)
   candidate_id:  27
   first_name:  Jordan
   surname:  Carter

5. Candidate  20  (Similitud: 0.316)
   candidate_id:  20
   first_name:  Rachel
   surname:  Lopez

--- Job details ---
job_post: Cybersecurity Analyst
company: Palo Alto Networks
minimum_work_experience: 4
max_work_experience: 8
education: Bachelor Cybersecurity
certifications: CISSP, Certified Ethical Hacker

TOP 5 CANDIDATES:

1. Candidate  36  (Similitud: 0.000)
   candidate_id:  36
   first_name:  Deborah
   surname:  Edwards

2. Candidate  35  (Similitud: 0.000)
   candidate_id:  35
   first_name:  Nathan
   surname:  Evans

3. Candidate  34  (Similitud: 0.000)
   candidate_id:  34
   first_name:  Sharon
   surname:  Parker

4. Candidate  33  (Similitud: 0.000)
   candidate_id:  33
   first_name:  Eric
   surname:  Campbell

5. Candidate  32  (Similitud: 0.000)
   candidate_id:  32
   first_name:  Angela
   surname:  Phillips

--- Job details ---
job_post: Supply Chain Manager
company: FedEx
minimum_work_experience: 5
max_work_experience: 10
education: Bachelor Supply Chain
certifications: APICS Certified, Logistics Management

TOP 5 CANDIDATES:

1. Candidate  36  (Similitud: 0.000)
   candidate_id:  36
   first_name:  Deborah
   surname:  Edwards

2. Candidate  35  (Similitud: 0.000)
   candidate_id:  35
   first_name:  Nathan
   surname:  Evans

3. Candidate  34  (Similitud: 0.000)
   candidate_id:  34
   first_name:  Sharon